name: Build and Extract Files from Docker Container

on:
  push:
    branches:
      - master

jobs:
  build-files-linux-x64:
    runs-on: ubuntu-22.04
    #if: ${{ false }}  # Set condition to false to make the workflow inactive

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Extract Files from Docker Container
        run: |
          # Build the Docker image from the Dockerfile in the repository
          docker build \
            --build-arg CPU_CORES=$(nproc) \
            --build-arg TICKER=PNY \
            --build-arg NAME=Peony \
            --build-arg BASE_NAME=peony \
            --build-arg TARGET=master \
            -t peony-linux-x64-build \
            -f contrib/docker/Dockerfile.dsw-linux-x64-wallet .

          # Start the container (if it's not already running)
          docker run -d --name peony-linux-x64-build-container peony-linux-x64-build

          # Create a temporary directory to hold the extracted files
          mkdir release_files

          # Copy files from the Docker container to the local filesystem
          docker cp peony-linux-x64-build-container:/PNY/deploy/linux-x64 release_files/

      - name: Archive and Upload Extracted Files
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: release_files
  build-files-linux-arm64:
    runs-on: ubuntu-22.04
    #if: ${{ false }}  # Set condition to false to make the workflow inactive

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Extract Files from Docker Container
        run: |
          # Build the Docker image from the Dockerfile in the repository
          docker build \
            --build-arg CPU_CORES=$(nproc) \
            --build-arg TICKER=PNY \
            --build-arg NAME=Peony \
            --build-arg BASE_NAME=peony \
            --build-arg TARGET=master \
            -t peony-linux-arm64-build \
            -f contrib/docker/Dockerfile.dsw-linux-arm64-wallet .

          # Start the container (if it's not already running)
          docker run -d --name peony-linux-arm64-build-container peony-linux-arm64-build

          # Create a temporary directory to hold the extracted files
          mkdir release_files

          # Copy files from the Docker container to the local filesystem
          docker cp peony-linux-arm64-build-container:/PNY/deploy/linux-arm64 release_files/

      - name: Archive and Upload Extracted Files
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: release_files
  build-windows-x64:
    runs-on: ubuntu-22.04
    #if: ${{ false }}  # Set condition to false to make the workflow inactive

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Extract Files from Docker Container
        run: |
          # Build the Docker image from the Dockerfile in the repository
          docker build \
            --build-arg CPU_CORES=$(nproc) \
            --build-arg TICKER=PNY \
            --build-arg NAME=Peony \
            --build-arg BASE_NAME=peony \
            --build-arg TARGET=master \
            -t peony-windows-x64-build \
            -f contrib/docker/Dockerfile.dsw-windows-x64-wallet .

          # Start the container (if it's not already running)
          docker run -d --name peony-windows-x64-build-container peony-windows-x64-build

          # Create a temporary directory to hold the extracted files
          mkdir release_files

          # Copy files from the Docker container to the local filesystem
          docker cp peony-windows-x64-build-container:/PNY/deploy/windows-x64 release_files/

      - name: Archive and Upload Extracted Files
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: release_files
  build-macos-x64:
    runs-on: ubuntu-22.04
    #if: ${{ false }}  # Set condition to false to make the workflow inactive

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build and Extract Files from Docker Container
        run: |
          # Build the Docker image from the Dockerfile in the repository
          docker build \
            --build-arg CPU_CORES=$(nproc) \
            --build-arg TICKER=PNY \
            --build-arg NAME=Peony \
            --build-arg BASE_NAME=peony \
            --build-arg TARGET=master \
            -t peony-macos-x64-build \
            -f contrib/docker/Dockerfile.dsw-macos-x64-wallet .

          # Start the container (if it's not already running)
          docker run -d --name peony-macos-x64-build-container peony-macos-x64-build

          # Create a temporary directory to hold the extracted files
          mkdir release_files

          # Copy files from the Docker container to the local filesystem
          docker cp peony-macos-x64-build-container:/PNY/deploy/macos-x64 release_files/

      - name: Archive and Upload Extracted Files
        uses: actions/upload-artifact@v3
        with:
          name: release-artifacts
          path: release_files
